export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const CALORIES_LOAD_REQUEST = 'CALORIES_LOAD_REQUEST'
export const CALORIES_LOAD_SUCCESS = 'CALORIES_LOAD_SUCCESS'
export const CALORIES_LOAD_FAILURE = 'CALORIES_LOAD_FAILURE'

export const USER = 'user'
export const ADMIN = 'admin'
