export const RECORD_LIST_REQUEST = 'RECORD_LIST_REQUEST'
export const RECORD_LIST_SUCCESS = 'RECORD_LIST_SUCCESS'
export const RECORD_LIST_FAILURE = 'RECORD_LIST_FAILURE'

export const RECORD_LOAD_REQUEST = 'RECORD_LOAD_REQUEST'
export const RECORD_LOAD_SUCCESS = 'RECORD_LOAD_SUCCESS'
export const RECORD_LOAD_FAILURE = 'RECORD_LOAD_FAILURE'

export const RECORD_UPDATE_REQUEST = 'RECORD_UPDATE_REQUEST'
export const RECORD_UPDATE_SUCCESS = 'RECORD_UPDATE_SUCCESS'
export const RECORD_UPDATE_FAILURE = 'RECORD_UPDATE_FAILURE'

export const RECORD_DELETE_REQUEST = 'RECORD_DELETE_REQUEST'
export const RECORD_DELETE_SUCCESS = 'RECORD_DELETE_SUCCESS'
export const RECORD_DELETE_FAILURE = 'RECORD_DELETE_FAILURE'

export const RECORD_ADD_REQUEST = 'RECORD_ADD_REQUEST'
export const RECORD_ADD_SUCCESS = 'RECORD_ADD_SUCCESS'
export const RECORD_ADD_FAILURE = 'RECORD_ADD_FAILURE'

export const RECORD_FILTER_REQUEST = 'RECORD_FILTER_REQUEST'
export const RECORD_FILTER_SUCCESS = 'RECORD_FILTER_SUCCESS'
export const RECORD_FILTER_FAILURE = 'RECORD_FILTER_FAILURE'

export const RECORD_CHANGE_TABLE_PAGE_REQUEST = 'RECORD_CHANGE_TABLE_PAGE_REQUEST'
export const RECORD_CHANGE_TABLE_PAGE_SUCCESS = 'RECORD_CHANGE_TABLE_PAGE_SUCCESS'
export const RECORD_CHANGE_TABLE_PAGE_FAILURE = 'RECORD_CHANGE_TABLE_PAGE_FAILURE'
