export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE'

export const USER_LOAD_REQUEST = 'USER_LOAD_REQUEST'
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS'
export const USER_LOAD_FAILURE = 'USER_LOAD_FAILURE'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAILURE = 'USER_DELETE_FAILURE'

export const USER_ADD_REQUEST = 'USER_ADD_REQUEST'
export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS'
export const USER_ADD_FAILURE = 'USER_ADD_FAILURE'

export const USER_CHANGE_TABLE_PAGE_REQUEST = 'USER_CHANGE_TABLE_PAGE_REQUEST'
export const USER_CHANGE_TABLE_PAGE_SUCCESS = 'USER_CHANGE_TABLE_PAGE_SUCCESS'
export const USER_CHANGE_TABLE_PAGE_FAILURE = 'USER_CHANGE_TABLE_PAGE_FAILURE'
